#!/usr/bin/env node
/**
 * Converts bible_notes/Bible-telugu/*.json (the source dataset, MIT
 * licensed — see bible_notes/Bible-telugu/LICENSE) into what the app
 * actually ships and reads: src/data/bible/books.json (the book index)
 * and src/data/bible/books/<slug>.json (one file per book), plus
 * src/data/bible/index.js, which is regenerated here too.
 *
 * Run it with: npm run generate:bible
 * It also runs automatically after `npm install` (see package.json
 * "postinstall") — but if you only *edit* something under bible_notes/
 * without reinstalling, run the command above yourself.
 *
 * Why index.js is generated rather than hand-written: Metro (the RN
 * bundler) needs every require() to have a literal string path it can see
 * at build time — it can't resolve `require(bookSlug + '.json')`. So this
 * script writes out one explicit `require('./books/<slug>.json')` per
 * book. Each is wrapped in a function (a "lazy require") so Metro still
 * bundles all 66 files, but none of them are actually parsed into memory
 * until the app opens that specific book — otherwise the app would parse
 * all ~13MB of Bible text on every cold start just to read one chapter.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'bible_notes', 'Bible-telugu');
const OUTPUT_DIR = path.join(ROOT, 'src', 'data', 'bible');
const OUTPUT_BOOKS_DIR = path.join(OUTPUT_DIR, 'books');

// Standard 66-book Protestant canon: the first 39 (Genesis–Malachi) are
// Old Testament, the remaining 27 (Matthew–Revelation) are New Testament.
const OLD_TESTAMENT_COUNT = 39;

function slugify(englishName) {
  return englishName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function main() {
  const booksIndexRaw = JSON.parse(fs.readFileSync(path.join(SOURCE_DIR, 'Books.json'), 'utf8'));

  fs.mkdirSync(OUTPUT_BOOKS_DIR, { recursive: true });

  const books = [];

  booksIndexRaw.forEach((entry, i) => {
    const english = entry.book.english.trim();
    const telugu = entry.book.telugu.trim();
    const slug = slugify(english);
    const sourceFile = path.join(SOURCE_DIR, `${english}.json`);

    if (!fs.existsSync(sourceFile)) {
      throw new Error(`Missing source file for "${english}" (expected ${sourceFile})`);
    }

    const bookData = JSON.parse(fs.readFileSync(sourceFile, 'utf8'));
    const chapterCount = bookData.chapters.length;

    fs.writeFileSync(
      path.join(OUTPUT_BOOKS_DIR, `${slug}.json`),
      JSON.stringify({ english, telugu, chapters: bookData.chapters }, null, 0),
      'utf8'
    );

    books.push({
      slug,
      english,
      telugu,
      chapterCount,
      testament: i < OLD_TESTAMENT_COUNT ? 'old' : 'new',
    });

    console.log(`  ${english} (${telugu}): ${chapterCount} chapters`);
  });

  fs.writeFileSync(path.join(OUTPUT_DIR, 'books.json'), JSON.stringify(books, null, 2), 'utf8');

  const loaderLines = books
    .map((b) => `  '${b.slug}': () => require('./books/${b.slug}.json'),`)
    .join('\n');

  const indexJs = `// GENERATED by scripts/generate-bible.js — do not hand-edit.
// Source data: bible_notes/Bible-telugu (MIT licensed, see its LICENSE file).
import books from './books.json';

// Lazy requires: Metro needs a literal string per require() call (that's
// why these are spelled out instead of built from a template), but each
// one only executes — parsing that book's JSON — the first time
// getBookData(slug) is actually called for it. Subsequent calls reuse
// Node/Metro's own require cache, so a book is parsed at most once per
// app session.
const BOOK_LOADERS = {
${loaderLines}
};

export const bibleBooks = books;

export function getBookBySlug(slug) {
  return books.find((b) => b.slug === slug) || null;
}

export function getBookData(slug) {
  const loader = BOOK_LOADERS[slug];
  return loader ? loader() : null;
}
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.js'), indexJs, 'utf8');

  console.log(`\nDone: ${books.length} books written to src/data/bible/`);
}

main();
